GOOSE_PROVIDER: anthropic
ANTHROPIC_HOST: https://api.anthropic.com
GOOSE_MODEL: claude-sonnet-4-0
extensions:
  agentqlmcp:
    args:
    - -y
    - agentql-mcp
    bundled: null
    cmd: npx
    description: AgentQL enables LLM's to open webpages and navigate them seamlessly.
    enabled: false
    env_keys: []
    envs: {}
    name: AgentQL MCP
    timeout: 300
    type: stdio
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  context7:
    bundled: null
    description: Context7 provides up to date API and code examples to guide code generation.
    enabled: true
    env_keys: []
    envs: {}
    name: context7
    timeout: 300
    type: sse
    uri: https://mcp.context7.com/sse
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  playwright-mcp:
    args:
    - -y
    - '@playwright/mcp@latest'
    bundled: null
    cmd: npx
    description: Leverage playright to browse websites and automate web interactions
    enabled: true
    env_keys: []
    envs: {}
    name: playwright-mcp
    timeout: 300
    type: stdio
  repomix:
    args:
    - --mcp
    bundled: null
    cmd: repomix
    description: Repomix automatically generates a single file of the contents of an entire git repository.
    enabled: true
    env_keys: []
    envs: {}
    name: repomix
    timeout: 300
    type: stdio
