{
  config,
  pkgs,
  ...
}: {
  stylix.targets.dank-material-shell.enable = true;

  programs.dank-material-shell = {
    enable = true;
    enableDynamicTheming = false;

    systemd.enable = false;
    niri.enableSpawn = true;

    niri.includes = {
      enable = true;
      override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [
        # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab" # Please note that niri will throw an error if any of these files are missing.
        "binds"
        "layout"
      ];
    };

    plugins = {
      dankterminaltheme.enable = true;
      wallpaperCarousel.enable = true;
      wallpaperShufflerPlugin.enable = true;

      aiAssistant.enable = true;
      aiOverviewControl.enable = true;
      codexBar.enable = true;

      nvidiaGpuMonitor.enable = true;
      networkIndicator.enable = true;
      nixMonitor.enable = true;
      dankDiskUsage.enable = true;
      resourceMonitor.enable = true;
      audioInhibit.enable = true;

      webSearch.enable = true;
      dankPomodoroTimer.enable = true;
      timer.enable = true;
      stopwatch.enable = true;
    };
  };

  home.packages = with pkgs; [
    curl
    jq
    wl-clipboard
  ];
}
