{
  config,
  lib,
  pkgs,
  ...
}: {
  config = lib.mkIf (config.me.desktop.shell == "dms") {
    stylix.targets.dank-material-shell.enable = true;

    programs.dank-material-shell = {
      enable = true;
      enableDynamicTheming = false;

      systemd.enable = false;
      niri.enableSpawn = true;

      niri.includes = {
        enable = true;
        override = true; # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
        originalFileName = "hm"; # A new name (without extension) for the config file generated by niri-flake.
        filesToInclude = [
          # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config.
          # Common niri layout, output, and bind behavior lives in ./niri-base.nix.
          "alttab" # Please note that niri will throw an error if any of these files are missing.
        ];
      };

      plugins = {
        dankterminaltheme.enable = true;
        wallpaperCarousel.enable = true;
        wallpaperShufflerPlugin.enable = true;

        aiAssistant.enable = true;
        aiOverviewControl.enable = true;
        codexBar.enable = true;

        nvidiaGpuMonitor.enable = true;
        networkIndicator.enable = true;
        nixMonitor.enable = true;
        dankDiskUsage.enable = true;
        resourceMonitor.enable = true;
        audioInhibit.enable = true;

        webSearch.enable = true;
        dankPomodoroTimer.enable = true;
        timer.enable = true;
        stopwatch.enable = true;
      };
    };

    programs.niri.settings.binds = {
      "Mod+Space" = {
        hotkey-overlay.title = "Application Launcher";
        action.spawn = ["dms" "ipc" "call" "spotlight" "toggle"];
      };
      "Mod+V" = {
        hotkey-overlay.title = "Clipboard Manager";
        action.spawn = ["dms" "ipc" "call" "clipboard" "toggle"];
      };
      "Mod+M" = {
        hotkey-overlay.title = "Task Manager";
        action.spawn = ["dms" "ipc" "call" "processlist" "focusOrToggle"];
      };
      "Super+X" = {
        hotkey-overlay.title = "Power Menu: Toggle";
        action.spawn = ["dms" "ipc" "call" "powermenu" "toggle"];
      };
      "Mod+Comma" = {
        hotkey-overlay.title = "Settings";
        action.spawn = ["dms" "ipc" "call" "settings" "focusOrToggle"];
      };
      "Mod+Y" = {
        hotkey-overlay.title = "Browse Wallpapers";
        action.spawn = ["dms" "ipc" "call" "dankdash" "wallpaper"];
      };
      "Mod+N" = {
        hotkey-overlay.title = "Notification Center";
        action.spawn = ["dms" "ipc" "call" "notifications" "toggle"];
      };
      "Mod+Shift+N" = {
        hotkey-overlay.title = "Notepad";
        action.spawn = ["dms" "ipc" "call" "notepad" "toggle"];
      };
      "Ctrl+Alt+Delete" = {
        hotkey-overlay.title = "Task Manager";
        action.spawn = ["dms" "ipc" "call" "processlist" "focusOrToggle"];
      };

      "XF86AudioRaiseVolume" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "audio" "increment" "3"];
      };
      "XF86AudioLowerVolume" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "audio" "decrement" "3"];
      };
      "XF86AudioMute" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "audio" "mute"];
      };
      "XF86AudioMicMute" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "audio" "micmute"];
      };
      "XF86AudioPause" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "mpris" "playPause"];
      };
      "XF86AudioPlay" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "mpris" "playPause"];
      };
      "XF86AudioPrev" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "mpris" "previous"];
      };
      "XF86AudioNext" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "mpris" "next"];
      };
      "Ctrl+XF86AudioRaiseVolume" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "mpris" "increment" "3"];
      };
      "Ctrl+XF86AudioLowerVolume" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "mpris" "decrement" "3"];
      };
      "XF86MonBrightnessUp" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "brightness" "increment" "5" ""];
      };
      "XF86MonBrightnessDown" = {
        allow-when-locked = true;
        action.spawn = ["dms" "ipc" "call" "brightness" "decrement" "5" ""];
      };

      "Mod+Shift+W" = {
        hotkey-overlay.title = "Create window rule";
        action.spawn = ["dms" "ipc" "call" "window-rules" "toggle"];
      };
      "Ctrl+Shift+R" = {
        hotkey-overlay.title = "Rename Workspace";
        action.spawn = ["dms" "ipc" "call" "workspace-rename" "open"];
      };
    };

    home.packages = with pkgs; [
      curl
      wl-clipboard
    ];
  };
}
